on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'fix/**'
      - 'release/**'
    paths-ignore:
      - '**/*.md'
      - .scafflater/**
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - '**/*.yaml'
      - .github/**
      - .scafflater/**
  workflow_dispatch:

name: package-kanbanize

env:
  app_name: 'commit-kanbanize'
  app_suffix: 'kanbanize'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: Install Hooks
        run: yarn install -g husky
      - name: Install Dependencies
        run: yarn install
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - run: yarn add -g husky
      - run: yarn install
      - run: yarn npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{secrets.APP_GITHUB_NAME}}
